### ISSUE TITLE
What is the current value when using a binary time dependent covariate

### ISSUE THREAD

**Issue by ElsaVazquez29** [DenisRustand/INLAjoint#22]
Hi Denis,

I am using the INLAjoint package to fit a joint model for a binary time-dependent covariate and a multistate model. I am interested in the current value association of the time-dependent covariate with the transitions in the multistate model. The question I have is, if the current value that is being associated with the transitions is the linear predictor related to the logit or the estimated probability of success based on the linear predictor?

Any guidance on this would be greatly appreciated.

Thank you in advance for your help!

Elsa Vazquez Arreola

**Comment by DenisRustand** [comment]
Hi Elsa,

The current value as implemented in INLAjoint is using the linear predictor (related to the logit).

Best,
Denis Rustand
